//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursemoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRATION
    {
        public int RID { get; set; }
        public string NetID { get; set; }
        public int CRN { get; set; }
        public bool Registered { get; set; }
        public bool WaitList { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
